language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files
env:
    global:
        - PHPUNIT_FLAGS="-v"

matrix:
    fast_finish: true
    include:
          # Minimum supported Symfony version with the latest PHP version
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

          # Test the latest stable release
        - php: 7.2
        - php: 7.3
          env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

          # Force some major versions of Symfony
        - php: 7.3
          env: DEPENDENCIES="dunglas/symfony-lock:^2"
        - php: 7.3
          env: DEPENDENCIES="dunglas/symfony-lock:^3"
        - php: 7.3
          env: DEPENDENCIES="dunglas/symfony-lock:^4"

          # Latest commit to master
        - php: 7.3
          env: STABILITY="dev"

    allow_failures:
          # Dev-master is allowed to fail.
        - env: STABILITY="dev"

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -z "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
    # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
    - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - composer validate --strict --no-check-lock
    - ./vendor/bin/phpunit $PHPUNIT_FLAGS
