sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: deps="low"
    - php: 5.6
      env: SYMFONY_VERSION=2.3.* PHPUNIT_VERSION=~3.7
    - php: 5.6
      env: SYMFONY_VERSION=2.0.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_VERSION=2.1.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_VERSION=2.2.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_VERSION=2.3.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_VERSION=2.4.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_VERSION=2.6.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_VERSION=2.7.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*@dev PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*@dev PHPUNIT_VERSION=~4.0
  allow_failures:
    - php: hhvm

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update "symfony/dependency-injection:${SYMFONY_VERSION}"; fi
  - if [ "$PHPUNIT_VERSION" != "" ]; then composer require --no-update "phpunit/phpunit:${PHPUNIT_VERSION}"; fi
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest; fi
  - if [ "$deps" = "" ]; then composer install; fi

script: vendor/bin/phpunit

notifications:
  email: matthiasnoback@gmail.com

cache:
  directories:
    - $COMPOSER_CACHE_DIR
