sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: SYMFONY_DI_VERSION=2.7.*
    - php: 7.0
      env: SYMFONY_DI_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_DI_VERSION=3.3.*
    - php: 7.0
      env: SYMFONY_DI_VERSION=4.0.*

cache:
  directories:
    - ~/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - if [ ! -z ${SYMFONY_VERSION+x} ]; then composer require --no-update "symfony/dependency-injection:${SYMFONY_VERSION}"; fi
  - composer install --prefer-dist

script: vendor/bin/phpunit

notifications:
  email: matthiasnoback@gmail.com

cache:
  directories:
    - $COMPOSER_CACHE_DIR
